#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# set the github API token for homebrew
HOMEBREW_GITHUB_API_TOKEN_PATH="$HOME/Dropbox/sync.dotfiles/brew.github.token.txt"
[[ -f $HOMEBREW_GITHUB_API_TOKEN_PATH ]] && export HOMEBREW_GITHUB_API_TOKEN=$(<$HOMEBREW_GITHUB_API_TOKEN_PATH)

## gnubin
# GNU_BIN="/usr/local/opt/coreutils/libexec/gnubin"
# [[ -d "$GNU_BIN" ]] && PATH="$GNU_BIN:$PATH"

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
# export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"
# export JAVA_HOME="$(/usr/libexec/java_home -v 13)"
# export JAVA11_HOME="$(/usr/libexec/java_home -v 11)"
# export JAVA13_HOME="$(/usr/libexec/java_home -v 13)"
# export JAVA8_HOME="$(/usr/libexec/java_home -v 1.8)"
# export JAVA7_HOME="$(/usr/libexec/java_home -v 1.7)"

# bin in home dir
HOME_BIN="$HOME/bin"
[[ -d "$HOME_BIN" ]] && PATH="$HOME_BIN:$PATH"

# gnu man
MANPATH_GNU="/usr/local/opt/findutils/libexec/gnuman"
[[ -d "$MANPATH_GNU" ]] && export MANPATH="$MANPATH_GNU:$MANPATH"

# android
ANDROID_HOME="$HOME/Library/Android/sdk"
if [[ -d "$ANDROID_HOME" ]]; then
    export ANDROID_HOME
    PATH="$ANDROID_HOME/platform-tools:$PATH"
fi

# anaconda3
ANACONDA3="/usr/local/anaconda3/bin"
[[ -d "$ANACONDA3" ]] && PATH="$ANACONDA3:$PATH"

# go
# GOROOT="$(brew --prefix golang)/libexec"
GOROOT="/usr/local/opt/go/libexec"
if [ -d "$GOROOT" ]; then
    export GOROOT
    export GOPATH="$HOME/.go"
    [[ -d "$GOPATH" ]] || mkdir -p "$GOPATH"
    [[ -d "$GOPATH/src/github.com" ]] || mkdir -p "$GOPATH/src/github.com"
    PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
fi

# ruby
RUBY_PATH="/usr/local/opt/ruby"
if [ -d "$RUBY_PATH" ]; then
    export LDFLAGS="$LDFLAGS -L$RUBY_PATH/lib"
    export CPPFLAGS="$CPPFLAGS -I$RUBY_PATH/include"
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$RUBY_PATH/lib/pkgconfig"
    PATH="$RUBY_PATH/bin:${PATH}"
fi

[[ -d /usr/local/opt/mongodb@3.4/bin ]] && PATH="/usr/local/opt/mongodb@3.4/bin:$PATH"

# disable to run Firefox in safe mode
export MOZ_DISABLE_SAFE_MODE_KEY="never"

# maven
export M2_HOME="/usr/local/opt/maven/libexec"

# curl
export PATH="/usr/local/opt/curl-openssl/bin:$PATH"

# misc
export PATH="$PATH:$HOME/hacker1/xsser"

# gettext
export PATH="/usr/local/opt/gettext/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/gettext/lib"
export CPPFLAGS="-I/usr/local/opt/gettext/include"

# node10 for angularjs 1.5.8
# export PATH="/usr/local/opt/node@10/bin:$PATH"

# doom
export PATH="$HOME/.emacs.d/bin:$PATH"

# kafka tools
export PATH="$PATH:/Users/akulynyak/tools/confluent-5.5.1/bin"

# the last one
export PATH=".:$PATH"

export SYSTEM_VERSION_COMPAT=1


