#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


bindkey -e
# bindkey '^R'      history-incremental-search-backward
bindkey "^[[5~"   up-line-or-history
bindkey "^[[6~"   down-line-or-history
bindkey "^[OH"    beginning-of-line
bindkey "^[[H"    beginning-of-line
bindkey "^[OF"    end-of-line
bindkey "^[[F"    end-of-line
bindkey '^[[1;3C' forward-word
bindkey '^[[C'    forward-word
bindkey '^[[1;3D' backward-word
bindkey '^[[D'    backward-word
bindkey '^[[C'    forward-char
bindkey '^[[D'    backward-char
bindkey '^?'      backward-delete-char
bindkey "^[[3~"   delete-char
bindkey "^[3;5~"  delete-char
bindkey '^[[3;5~' delete-word
bindkey '^H'      backward-delete-word
# space during searches
bindkey -M isearch " " magic-space

# edit the current command line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
# bindkey -M menuselect " " accept-and-menu-complete

autoload -U url-quote-magic
zle -N self-insert url-quote-magic

alias vi="$EDITOR"
alias vim="$EDITOR"
alias svi="sudo $EDITOR"
alias snano="sudo nano"

alias x='exit'
alias zreload='exec zsh'

alias hist='fc -l 1'

alias dud='du -s *(/)' # show directories size

unalias rm
alias rm='trash'

unalias l
alias l='ls -la' # Lists in one column, hidden files.

alias pgrep='pgrep -f'

alias pkill='pkill -9 -f'

alias port='netstat -ntlp tcp' # opening ports

alias pyshare='python3 -m http.server' # share current folder

function lsgrep() {
  # about 'search through directory contents with grep'
  gls -l | grep -E -i "$*"
}

function quiet() {
  # about 'what *does* this do?'
  $* &>/dev/null &
}

function buf() {
  # about 'back up file with timestamp'
  # param 'filename'
  local filename=$1
  local filetime=$(date +%Y%m%d_%H%M%S)
  cp -a "${filename}" "${filename}_${filetime}"
}

function explain() {
  # about 'explain any bash command via mankier.com manpage API'
  # param '1: Name of the command to explain'
  # example '$ explain                # interactive mode. Type commands to explain in REPL'
  # example '$ explain '"'"'cmd -o | ...'"'"' # one quoted command to explain it.'
  if [ "$#" -eq 0 ]; then
    while read -p "Command: " cmd; do
      curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols) --data-urlencode "q=$cmd"
    done
    echo "Bye!"
  elif [ "$#" -eq 1 ]; then
    curl -Gs "https://www.mankier.com/api/explain/?cols="$(tput cols) --data-urlencode "q=$1"
  else
    echo "Usage"
    echo "explain                  interactive mode."
    echo "explain 'cmd -o | ...'   one quoted command to explain it."
  fi
}

function sshlist() {
  # about 'list hosts defined in ssh config'
  awk '$1 ~ /Host$/ {for (i=2; i<=NF; i++) print $i}' ~/.ssh/config
}


